<?php

/**
 * ProcessWire Phone Fieldtype
 * by Adrian Jones with code from "Soma" Philipp Urlich's Dimension Fieldtype module
 *
 * Field that stores 4 integer values for country/area code/number/extension.
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class FieldtypePhone extends Fieldtype {


    public static function getModuleInfo() {
        return array(
            'title' => __('Phone Fieldtype', __FILE__), // Module Title
            'summary' => __('Field that stores 4 integer values for country, area code, number, extension.', __FILE__), // Module Summary
            'version' => 100,
            'author' => 'Adrian',
            'installs' => 'InputfieldPhone'
        );
    }

    /**
     * Format value for output
     *
     */
    public function ___formatValue(Page $page, Field $field, $value) {
        return $value;
    }

    /**
     *
     * Add mapping to different name for use in page selectors
     * This enables us to use it like "field.country=61, field.area_code=225, field.number=123456, field.extension=123"
     */
    public function getMatchQuery($query, $table, $subfield, $operator, $value) {
        if($subfield == 'country') $subfield = 'data';
        if($subfield == 'area_code') $subfield = 'data_area_code';
        if($subfield == 'number') $subfield = 'data_number';
        if($subfield == 'extension') $subfield = 'data_extension';
        return parent::getMatchQuery($query, $table, $subfield, $operator, $value);
    }

    /**
     * get Inputfield for this fieldtype, set config attributes so they can be used in the inputfield
     *
     */
    public function getInputfield(Page $page, Field $field) {
        $dim = $this->modules->get('InputfieldPhone');
        return $dim;
    }

    /**
     * there's none compatible
     *
     */
    public function ___getCompatibleFieldtypes(Field $field) {
        return null;
    }

    /**
     * blank value is an WireData object Phone
     *
     */
    public function getBlankValue(Page $page, Field $field) {
        return new Phone();
    }

    /**
     * Any value will get sanitized before setting it to a page object
     * and before saving the data
     *
     * If value not of instance Phone return empty instance
     */
    public function sanitizeValue(Page $page, Field $field, $value) {

        if(!$value instanceof Phone) $value = $this->getBlankValue($page, $field);

        // report any changes to the field values
        if($value->isChanged('country')
                || $value->isChanged('area_code')
                || $value->isChanged('number')
                || $value->isChanged('extension')) {
            $page->trackChange($field->name);
        }

        return $value;
    }

    /**
     * get values converted when fetched from db
     *
     */
    public function ___wakeupValue(Page $page, Field $field, $value) {

        // get blank dim
        $dim = $this->getBlankValue($page, $field);

        // populate the dim
        $dim->country = (int) $value['data'];
        $dim->area_code = (int) $value['data_area_code'];
        $dim->number = (int) $value['data_number'];
        $dim->extension = (int) $value['data_extension'];

        return $dim;
    }

    /**
     * return converted from object to array for storing in database
     *
     */
    public function ___sleepValue(Page $page, Field $field, $value) {

        // throw error if value is not of the right type
        if(!$value instanceof Phone)
            throw new WireException("Expecting an instance of Phone");

        $sleepValue = array(
            'data' => (int) $value->country,
            'data_area_code' => (int) $value->area_code,
            'data_number' => (int) $value->number,
            'data_extension' => (int) $value->extension
            );

        return $sleepValue;
    }

    /**
     * Get the database schema for this field
     *
     * @param Field $field In case it's needed for the schema, but usually should not.
     * @return array
     */
    public function getDatabaseSchema(Field $field) {

        $schema = parent::getDatabaseSchema($field);
        $schema['data'] = 'int NOT NULL default 0';
        $schema['data_area_code'] = 'int NOT NULL default 0';
        $schema['data_number'] = 'int NOT NULL default 0';
        $schema['data_extension'] = 'int NOT NULL default 0';
        // key for data will already be added from the parent
        $schema['keys']['data_area_code'] = 'KEY data_height(data_area_code)';
        $schema['keys']['data_number'] = 'KEY data_depth(data_number)';
        $schema['keys']['data_extension'] = 'KEY data_volume(data_extension)';
        return $schema;
    }

    /**
     * Get any inputfields used for configuration of this Fieldtype.
     *
     * This is in addition any configuration fields supplied by the parent Inputfield.
     *
     * @param Field $field
     * @return InputfieldWrapper
     *
     */
    public function ___getConfigInputfields(Field $field) {
        $inputfields = parent::___getConfigInputfields($field);
        // nothing yet
        return $inputfields;
    }

}


/**
 * Helper WireData Class to hold a Phone object
 *
 */
class Phone extends WireData {

    public function __construct() {
        $this->set('country', null);
        $this->set('area_code', null);
        $this->set('number', null);
        $this->set('extension', null);
    }

    public function set($key, $value) {

        if($key == 'country' || $key == 'area_code' || $key == 'number' || $key == 'extension') {
            // if value isn't numeric, don't change the value if already
            // one set, else set it to 0 and throw an exception so it can be seen on API usage
            if(!is_int($value) && !is_null($value)) {
                $value = $this->$key ? $this->$key : 0;
                throw new WireException("Phone Object only accepts integers (int) values");
            }
        }
        return parent::set($key, $value);
    }

    public function get($key) {
        return parent::get($key);
    }

}
