<?php

/**
 * ProcessWire Phone Fieldtype
 * by Adrian Jones with code from "Soma" Philipp Urlich's Dimensions Fieldtype module and Ryan's core FieldtypeDatetime module
 *
 * Field that stores 4 numeric values for country/area code/number/extension and allows for multiple formatting options.
 *
 * ProcessWire 3.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class FieldtypePhone extends Fieldtype implements Module, ConfigurableModule {


    public static function getModuleInfo() {
        return array(
            'title' => __('Phone', __FILE__),
            'summary' => __('Multi part phone field, with custom output formatting options.', __FILE__),
            'version' => '2.0.6',
            'author' => 'Adrian Jones',
            'href' => 'http://modules.processwire.com/modules/fieldtype-phone/',
            'installs' => 'InputfieldPhone',
            'requiredBy' => 'InputfieldPhone',
            'icon' => 'phone'
       );
    }

    protected static $configDefaults = array(

        "example_country" => 1,
        "example_area_code" => 012,
        "example_number" => 3456789,
        "example_extension" => 123,
        "output_format" => "",
        "output_format_options" => "northAmericaStandard | {+[phoneCountry] }{([phoneAreaCode]) }{[phoneNumber,0,3]-}{[phoneNumber,3,4]}{ x[phoneExtension]}
northAmericaNoNumberDashes | {+[phoneCountry] }{([phoneAreaCode]) }{[phoneNumber]}{ x[phoneExtension]}
northAmericaAllDashes| {+[phoneCountry]-}{[phoneAreaCode]-}{[phoneNumber,0,3]-}{[phoneNumber,3,4]}{ x[phoneExtension]}
northAmericaDashesNoNumberDashes | {+[phoneCountry]-}{[phoneAreaCode]-}{[phoneNumber]}{ x[phoneExtension]}
australiaNoCountryAreaCodeLeadingZero | {([phoneAreaCode,0,2]) }{[phoneNumber,0,4] }{[phoneNumber,4,4]}{ x[phoneExtension]}
australiaWithCountryAreaCodeNoLeadingZero | {+[phoneCountry] }{([phoneAreaCode,1,1]) }{[phoneNumber,0,4] }{[phoneNumber,4,4]}{ x[phoneExtension]}"
   );


    /**
     * Data as used by the get/set functions
     *
     */
    protected $data = array();

    /**
     * Format the value for output, according to selected format and language
     *
     */
    public function ___formatValue(Page $page, Field $field, $value) {

        if($value->output_format) {
            $output_format = $value->output_format;
        }
        elseif($field->output_format) {
            $output_format = $field->output_format;
        }
        else {
            $output_format = $this->data["output_format"];
        }

        $outputCode = $this->getFormatFromName($output_format);

        $value->formattedNumber = $this->formatPhone($value->country, $value->area_code, $value->number, $value->extension, $outputCode);
        $value->formattedNumberNoCtryNoExt = $this->formatPhone(null, $value->area_code, $value->number, null, $outputCode);
        $value->formattedNumberNoCtry = $this->formatPhone(null, $value->area_code, $value->number, $value->extension, $outputCode);
        $value->formattedNumberNoExt = $this->formatPhone($value->country, $value->area_code, $value->number, null, $outputCode);

        $value->unformattedNumberNoCtryNoExt = ($value->area_code ? $value->area_code : null) . ($value->number ? $value->number : null);
        $value->unformattedNumberNoCtry = ($value->area_code ? $value->area_code : null) . ($value->number ? $value->number : null) . ($value->extension ? $value->extension : null);
        $value->unformattedNumberNoExt = ($value->country ? $value->country : null) . ($value->area_code ? $value->area_code : null) . ($value->number ? $value->number : null);
        $value->unformattedNumber = $value->unformattedNumberNoExt . ($value->extension ? $value->extension : null);

        foreach(explode("\n",$this->data["output_format_options"]) as $format) {
            if(trim(preg_replace('!/\*.*?\*/!s', '', $format)) == '') continue;
            $formatParts = explode('|', $format);
            $formatName = trim($formatParts[0]);
            $formatCode = trim($formatParts[1]);
            $value->$formatName = $this->formatPhone($value->country, $value->area_code, $value->number, $value->extension, $formatCode);
        }

        return $value;
    }

    /**
     * Format the value for string output, eg in a Lister table
     *
     */
    public function ___markupValue(Page $page, Field $field, $value = null, $property = '') {
        if(is_null($value)) return;
        $output_format = isset($field->data["output_format"]) ? $field->data["output_format"] : $this->data["output_format"];
        $outputCode = $this->getFormatFromName($output_format);
        return $this->formatPhone($value->country, $value->area_code, $value->number, $value->extension, $outputCode);
    }

    /**
     *
     * Add mapping to different name for use in page selectors
     * This enables us to use it like "field.country=61, field.area_code=225, field.number=123456, field.extension=123"
     */
    public function getMatchQuery($query, $table, $subfield, $operator, $value) {
        if($subfield == 'country') $subfield = 'data';
        if($subfield == 'area_code') $subfield = 'data_area_code';
        if($subfield == 'number') $subfield = 'data_number';
        if($subfield == 'extension') $subfield = 'data_extension';
        return parent::getMatchQuery($query, $table, $subfield, $operator, $value);
    }

    /**
     * get Inputfield for this fieldtype, set config attributes so they can be used in the inputfield
     *
     */
    public function getInputfield(Page $page, Field $field) {
        $pn = $this->wire('modules')->get('InputfieldPhone');
        return $pn;
    }

    /**
     * there's none compatible
     *
     */
    public function ___getCompatibleFieldtypes(Field $field) {
        return null;
    }

    /**
     * blank value is an WireData object Phone
     *
     */
    public function getBlankValue(Page $page, Field $field) {
        return new Phone();
    }

    /**
     * Any value will get sanitized before setting it to a page object
     * and before saving the data
     *
     * If value not of instance Phone return empty instance
     */
    public function sanitizeValue(Page $page, Field $field, $value) {

        if(!$value instanceof Phone) $value = $this->getBlankValue($page, $field);

        // report any changes to the field values
        if($value->isChanged('country')
            || $value->isChanged('area_code')
            || $value->isChanged('number')
            || $value->isChanged('extension')
            || $value->isChanged('output_format')) {
                $page->trackChange($field->name);
        }
        return $value;
    }

    /**
     * get values converted when fetched from db
     *
     */
    public function ___wakeupValue(Page $page, Field $field, $value) {

        // get blank phone number (pn)
        $pn = $this->getBlankValue($page, $field);

        // populate the pn
        if(isset($value['data'])) $pn->country = $this->wire('sanitizer')->digits($value['data']);
        if(isset($value['data_area_code'])) $pn->area_code = $this->wire('sanitizer')->digits($value['data_area_code']);
        if(isset($value['data_number'])) $pn->number = $this->wire('sanitizer')->digits($value['data_number']);
        if(isset($value['data_extension'])) $pn->extension = $this->wire('sanitizer')->digits($value['data_extension']);
        if(isset($value['data_output_format'])) $pn->output_format = $this->wire('sanitizer')->digits($value['data_output_format']);

        return $pn;
    }

    /**
     * return converted from object to array for storing in database
     *
     */
    public function ___sleepValue(Page $page, Field $field, $value) {

        // throw error if value is not of the right type
        if(!$value instanceof Phone)
            throw new WireException("Expecting an instance of Phone");

        $sleepValue = array(
            'data' => $this->wire('sanitizer')->digits($value->country),
            'data_area_code' => $this->wire('sanitizer')->digits($value->area_code),
            'data_number' => $this->wire('sanitizer')->digits($value->number),
            'data_extension' => $this->wire('sanitizer')->digits($value->extension),
            'data_output_format' => $this->wire('sanitizer')->digits($value->output_format)
       );

        return $sleepValue;
    }

    /**
     * Get the database schema for this field
     *
     * @param Field $field In case it's needed for the schema, but usually should not.
     * @return array
     */
    public function getDatabaseSchema(Field $field) {

        $schema = parent::getDatabaseSchema($field);
        $schema['data'] = 'varchar(15) NOT NULL';
        $schema['data_area_code'] = 'varchar(15) NOT NULL';
        $schema['data_number'] = 'varchar(15) NOT NULL';
        $schema['data_extension'] = 'varchar(15) NOT NULL';
        $schema['data_output_format'] = 'varchar(255) NOT NULL';
        // key for data will already be added from the parent
        $schema['keys']['data_area_code'] = 'KEY data_area_code(data_area_code)';
        $schema['keys']['data_number'] = 'KEY data_number(data_number)';
        $schema['keys']['data_extension'] = 'KEY data_extension(data_extension)';
        $schema['keys']['data_output_format'] = 'KEY data_output_format(data_output_format)';
        return $schema;
    }

    /**
     * Get any inputfields used for configuration of this Fieldtype.
     *
     * This is in addition to any configuration fields supplied by the parent Inputfield.
     *
     * @param Field $field
     * @return InputfieldWrapper
     *
     */
    public function getModuleConfigInputfields(array $data) {

        $modules = $this->wire('modules');
        $config = $this->wire('config');

        $modules->addHookBefore('saveModuleConfigData', null, 'InputfieldPhone_saveModuleConfigData');

        foreach(self::$configDefaults as $key => $value) {
            if(!isset($data[$key]) || $data[$key]=='' || $data[$key]=='~') $data[$key] = $value;
        }
        $this->data = array_map(array($this, 'removeTilde'), $data);

        $inputfields = new InputfieldWrapper();

        $f = $modules->get('InputfieldSelect');
        $f->attr('name', 'output_format');
        $f->label = __('Phone Output Format', __FILE__);
        $f->description = __("Select the default format to be used when outputting phone numbers.\n\nYou can define new formats for this dropdown select in the 'Phone Output Format Options' field below.", __FILE__);
        $f->notes = __("This can be overridden on the Input tab of each 'phone' field.", __FILE__);
        $f->addOption('', __('None', __FILE__));
        foreach($this->buildOptions(explode("\n",$this->data["output_format_options"]), $this->data) as $option) {
            $f->addOption($option[0], $option[1]);
            if($this->data["output_format"] == $option[0]) $f->attr('value', $option[0]);
        }
        $inputfields->add($f);

        $f = $modules->get("InputfieldTextarea");
        $f->attr('name', 'output_format_options');
        $f->attr('value', $this->data["output_format_options"]);
        $f->attr('rows', 10);
        $f->label = __('Phone Output Format Options', __FILE__);
        $f->description = __("Edit the defined formats here.\nOnce saved, they will be available for the default Phone Output Format selector on this page, as well as the Format Override selector when entering data for phone number fields.\n\nOne format per line.\n\nEach component of the phone number is surrounded by { }\nThe names of the component parts are surrounded by [ ]\nTwo optional comma separated numbers after the component name are used to get certain parts of the number using php's substr function, allowing for complete flexibility.\nAnything outside the [ ] is used directly: +,-,(,),x, spaces, etc - whatever you want to use.\n\nYou can reset to the default options by emptying this field and saving.\n\nPlease send me a PR on Github, or post to the support forum any new formats you create that you think others would find useful.", __FILE__);
        $f->collapsed = Inputfield::collapsedYes;
        $inputfields->add($f);

        $fieldset = $modules->get("InputfieldFieldset");
        $fieldset->attr('id', 'example_number_options');
        $fieldset->label = __('Example Number Options', __FILE__);
        $fieldset->collapsed = Inputfield::collapsedYes;
        $inputfields->add($fieldset);

        $f = $modules->get("InputfieldText");
        $f->attr('name', 'example_country');
        $f->attr('value', $this->data["example_country"]);
        $f->attr('size', 20);
        $f->label = __('Example Country Code', __FILE__);
        $f->description = __('The number(s) you want to use for the country code in the format example.', __FILE__);
        $fieldset->add($f);

        $f = $modules->get("InputfieldText");
        $f->attr('name', 'example_area_code');
        $f->attr('value', $this->data["example_area_code"]);
        $f->attr('size', 20);
        $f->label = __('Example Area Code', __FILE__);
        $f->description = __('The number(s) you want to use for the area code in the format example.', __FILE__);
        $fieldset->add($f);

        $f = $modules->get("InputfieldText");
        $f->attr('name', 'example_number');
        $f->attr('value', $this->data["example_number"]);
        $f->attr('size', 20);
        $f->label = __('Example Phone Number', __FILE__);
        $f->description = __('The numbers you want to use for the phone number in the format example.', __FILE__);
        $fieldset->add($f);

        $f = $modules->get("InputfieldText");
        $f->attr('name', 'example_extension');
        $f->attr('value', $this->data["example_extension"]);
        $f->attr('size', 20);
        $f->label = __('Example Extension', __FILE__);
        $f->description = __('The number(s) you want to use for the extension in the format example.', __FILE__);
        $fieldset->add($f);

        return $inputfields;
    }


    /**
     * Format a phone number with the given number format
     *
     * @param text $phoneCountry country code
     * @param text $phoneAreaCode area code
     * @param text $phoneNumber number
     * @param text $phoneExtension phone extension
     * @param string $format to use for formatting
     * @return string Formatted phone string
     *
     */
    public function formatPhone($phoneCountry, $phoneAreaCode, $phoneNumber, $phoneExtension, $format) {

        if(!$phoneNumber) return '';
        if(!strlen($format) || $format == '%s') return ($phoneCountry ? $phoneCountry : null) . ($phoneAreaCode ? $phoneAreaCode : null) . ($phoneNumber ? $phoneNumber : null) . ($phoneExtension ? $phoneExtension : null); // no formatting

        $pattern = preg_match_all("/{(.*?)}/", $format, $components);

        $finalvalue = '';

        foreach ($components[1] as $component) {
            $prefix = strstr($component, '[', TRUE);
            $suffix = str_replace(']','',strstr($component, ']'));

            $component = str_replace(array($prefix, $suffix, '[', ']'), null, $component);

            if(strcspn($component, '0123456789') != strlen($component)) {
                    $component_name = strstr($component, ',', TRUE);
                    $char_cutoffs = explode(',',ltrim(str_replace($component_name, '', $component),','));
                    $value = substr($$component_name, $char_cutoffs[0], $char_cutoffs[1]);
            }
            else {
                $component_name = $component;
                $value = $$component_name;
            }

            $finalvalue .= ($value != '' ? $prefix . $value . $suffix : null);
        }
        return $finalvalue;
    }

    /**
     * Helper function to remove any ~ from the format example numbers
     *
     */
    public function removeTilde($value) {
        return is_string($value) ? str_replace('~', '', $value) : $value;
    }


    public function buildOptions($options, $data) {
        $optionsArr = array();
        foreach($options as $format) {
            if(trim(preg_replace('!/\*.*?\*/!s', '', $format)) == '') continue;
            $formatParts = explode('|', $format);
            $formatName = trim($formatParts[0]);
            $formatCode = trim($formatParts[1]);
            $phoneNumberFormatted = $this->formatPhone($data["example_country"], $data["example_area_code"], $data["example_number"], $data["example_extension"], $formatCode);
            $optionsArr[] = array($formatName, $formatName . ' | ' . $this->removeTilde($phoneNumberFormatted));
        }
        return $optionsArr;
    }

    public function getFormatFromName($formatName) {
        foreach(explode("\n",$this->data['output_format_options']) as $format) {
            if(trim(preg_replace('!/\*.*?\*/!s', '', $format)) == '') continue;
            $formatParts = explode('|', $format);
            if(trim($formatParts[0]) == $formatName) {
                return trim($formatParts[1]);
            }
        }
    }


    public function ___install() {
        // save default config data on install
        $this->wire('modules')->saveModuleConfigData($this, self::$configDefaults);
    }

}


/**
 * Helper function to prepend a ~ to the format example numbers to prevent wireEncodeJSON from stripping leading zeros
 *
 */
function InputfieldPhone_saveModuleConfigData(HookEvent $event) {
    $arguments = $event->arguments;
    if($arguments[0] != 'FieldtypePhone') return;
    $data = $arguments[1];
    foreach ($data as $key => $value) {
        $data[$key] = strpos($key,'example_') !== false  ? '~' . $value : $value;
    }
    $name = 'replacements';
    if(!is_array($data[$name])) $data[$name] = InputfieldPageName::replacementStringToArray($data[$name]);
    $arguments[1] = $data;
    $event->arguments = $arguments;
}


/**
 * Helper WireData Class to hold a Phone object
 *
 */
class Phone extends WireData {

    public function __construct() {
        $this->set('country', null);
        $this->set('area_code', null);
        $this->set('number', null);
        $this->set('extension', null);
        $this->set('output_format', null);
    }

    public function set($key, $value) {

        if($key == 'country' || $key == 'area_code' || $key == 'number' || $key == 'extension') {
            // if value isn't numeric set it to blank and throw an exception so it can be seen on API usage
            if(!is_numeric($value) && !is_null($value) && $value != '') {
                $value = $this->$key ? $this->$key : '';
                throw new WireException("Phone Object only accepts numbers");
            }
        }
        return parent::set($key, $value);
    }

    public function get($key) {
        return parent::get($key);
    }

    public function __toString() {
        $number = (string)$this->formattedNumber ? (string)$this->formattedNumber : $this->data['number'];
        if(!$number) $number = '';
        return $number;
    }

}