<?php

/**
 * ProcessWire Phone Inputfieldtype
 * by Adrian Jones with code from "Soma" Philipp Urlich's Dimensions Fieldtype module and Ryan's core FieldtypeDatetime module
 *
 * ProcessWire 3.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class InputfieldPhone extends Inputfield {

    public static function getModuleInfo() {
        return array(
            'title' => __('Phone Inputfield', __FILE__),
            'summary' => __('Multi part phone field, with custom output formatting options.', __FILE__),
            'version' => '2.0.0',
            'author' => 'Adrian Jones',
            'href' => 'http://modules.processwire.com/modules/fieldtype-phone/',
            'icon' => 'phone',
            'requires' => array("FieldtypePhone")
       );
    }


    /**
     * Construct the Inputfield, setting defaults for all properties
     *
     */
    public function __construct() {
        $this->set('input_width', 100);
        $this->set('input_country', 0);
        $this->set('input_extension', 0);
        $this->set('input_output_format_override', 0);

        $this->fieldtypePhone = $this->wire('modules')->get('FieldtypePhone');

        $this->data = array_map(array($this->fieldtypePhone, 'removeTilde'), $this->fieldtypePhone->getArray());

        $this->set('output_format',$this->data["output_format"]);
        $this->set('output_format_options',$this->data["output_format_options"]);
        $this->set('example_country', $this->data["example_country"]);
        $this->set('example_area_code', $this->data["example_area_code"]);
        $this->set('example_number', $this->data["example_number"]);
        $this->set('example_extension', $this->data["example_extension"]);
        parent::__construct();

    }

    /**
     * Per the Module interface, init() is called when the system is ready for API usage
     *
     */
    public function init() {
        return parent::init();
    }

    /**
     * Return the completed output of this Inputfield, ready for insertion in an XHTML form
     *
     * @return string
     *
     */
    public function ___render() {

        $out = '';

        $value = $this->attr('value') ? $this->attr('value') : new \Phone();

        if($this->hasField->data['input_country'] == 1) {
            $out .= "<div class='phone_col'>";
            $out .= "<label>{$this->_("Country Code")}: <input type='text' pattern='[0-9]*' style='width:{$this->input_width}px' name='{$this->name}_country' id='Inputfield_{$this->name}_country' value='{$value->country}'/></label>";
            $out .= "</div>";
        }

        $out .= "<div class='phone_col'>";
        $out .= "<label>{$this->_("Area Code")}: <input type='text' pattern='[0-9]*' style='width:{$this->input_width}px' name='{$this->name}_area_code' id='Inputfield_{$this->name}_area_code' value='{$value->area_code}'/></label>";
        $out .= "</div>";

        $out .= "<div class='phone_col'>";
        $out .= "<label>{$this->_("Number")}: <input type='text' pattern='[0-9]*' style='width:{$this->input_width}px' name='{$this->name}_number' id='Inputfield_{$this->name}_number' value='{$value->number}'/></label>";
        $out .= "</div>";

        if($this->hasField->data['input_extension'] == 1) {
            $out .= "<div class='phone_col'>";
            $out .= "<label>{$this->_("Extension")}: <input type='text' pattern='[0-9]*' style='width:{$this->input_width}px' name='{$this->name}_extension' id='Inputfield_{$this->name}_extension' value='{$value->extension}'/></label>";
            $out .= "</div>";
        }

        if($this->hasField->data['input_output_format_override'] == 1) {

            $out .= "<br /><br /><br /><div class='phone_col'>";
            $out .= "<label>{$this->_("Format Override")}: <select name='{$this->name}_output_format' id='Inputfield_{$this->name}_output_format'>";
            $out .= '<option value="" ' . ($this->output_format == '' ? 'selected' : '') . '>No Override</option>';
            $this->fieldtypePhone = $this->wire('modules')->get('FieldtypePhone');
            foreach($this->fieldtypePhone->buildOptions(explode("\n",$this->data["output_format_options"]), $this->data) as $option) {
                $out .= '<option value="'.$option[0].'" ' . (($option[0] == $this->output_format) ? 'selected' : '') . '>'.$option[1].'</option>';
            }
            $out .= "</select></label>";
            $out .= "</div>";
        }

        $out .= '<div style="clear:both">&nbsp;</div>';

        return $out;
    }

    /**
     * Process the input from the given WireInputData (usually $input->get or $input->post), load and clean the value for use in this Inputfield.
     *
     * @param WireInputData $input
     * @return $this
     *
     */
    public function ___processInput(WireInputData $input) {

        $name = $this->attr('name');
        $value = $this->attr('value');

        if(is_null($value)) $value = new \Phone;

        $pn_names = array(
            'country' => $name . "_country",
            'area_code' => $name . "_area_code",
            'number' => $name . "_number",
            'extension' => $name . "_extension",
            'output_format' => $name . "_output_format"
       );

        // loop all inputs and set them if changed
        foreach($pn_names as $key => $name) {
            if(isset($input->$name)) {
                if($value->$key !== $input->$name) {
                    if(!is_numeric($input->$name) && !empty($input->$name) && $key != 'output_format') {
                        // in case the input isn't numeric show an error
                        $this->wire()->error($this->_("Field only accepts numeric values"));
                    } else {
                        $value->set($key, $this->wire('sanitizer')->digits($input->$name));
                    }
                }
            }
        }
        if($value != $this->attr('value')) {
            $this->trackChange('value');
            $this->setAttribute('value', $this->fieldtypePhone->formatPhone($value->country, $value->area_code, $value->number, $value->extension, $this->fieldtypePhone->getFormatFromName($this->output_format)));
        }
        return $this;
    }

    public function getFormattedNumber() {
        return 'test';
    }

}
